# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'
# - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    solution: '**/*.sln'
    configuration: $(buildConfiguration)
    logProjectEvents: true


# Run Unit Tests
# - task: DotNetCoreCLI@2
#   inputs:
#     command: test
#     projects: '**/*tests/*.csproj'
#     arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

# Copy all the nupkg files created to the artifact directory
- task: CopyFiles@2
  displayName: 'Copy nupkg to StagingDirectory - $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**\*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts to drop location'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
   